apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cs3219
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: cs3219/api-gateway:1.0.0
          ports:
            - containerPort: 7000
