apiVersion: v1
kind: Service
metadata:
  namespace: cs3219
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - protocol: TCP
      port: 8080
      targetPort: 8080
